---
title: "Data Import and Basic Management"
author: "Jack Sudds"
date: "2024-12-20"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r Packages}
if (!require("pacman")) install.packages("pacman")
library(pacman)
p_load(
  #Learning & Base
  learnr, swirl, installr,
  #File & Package Management
  here, rio, openxlsx, renv, pacman, remotes, readxl,
  #Data Management
  tidyverse, linelist, naniar, parsedate, reshape2, dplyr,
  #Stats
  janitor, gtsummary, rstatix, broom, lmtest, easystats, skimr, spatstat,
  #Plots
  cowplot, RColorBrewer, ggnewscale, wesanderson, DiagrammeR, incidence2, gghighlight, ggtext, ggrepel, gganimate, ggsci, grates, gridExtra, ggforce, hexbin, plotly,
  #GIS
  sf, tmap, spdep, rnaturalearth, rnaturalearthdata, broom, ggmap, mapdata, maps, spData, BiocManager, geoR, giscoR,
  #Reports & Dashboards
  rmarkdown, reportfactory, officer, flexdashboard, shiny,
  #tables
  knitr, flextable, formattable, gt,
  #Other
  kableExtra, psych, BSDA, htmltools, rgl, lubridate, htmlwidgets,
  #Testing
  raster, dismo, terra, CCAMLRGIS, tigris, patchwork
)
```

```{r Import methods}
rm(list = ls(all.names = TRUE))
#Read from file in same directory
#<name of df> <- read.xlsx(here("file name.xlsx"), sheet = "Sheet name", range = "A1:E33")
data1_base <- read.xlsx(here("Data/data.xlsx"), sheet = "skeletal_part_abundances")
data2_base <- read.xlsx(here("Data/data_2.xlsx"), sheet = "Sheep_Mandibles")
#<name of df> <- read.csv(here("File name.csv"))

#Write to file types
#write.xlsx(<Name of Object>, file = "<File name>.xlsx")
#write.csv(<Name of Object>, file = "<File name>.csv")

data3_base <- iris
data5_base <- mtcars
```

```{r Basic normalisation}
#create copy of object
data1 <- data1_base
data2 <- data2_base
data3 <- data3_base
data5 <- data5_base
#automatic name changes
data2 <- data2 %>%
  janitor::clean_names()
#change column names of specific ones by number
colnames(data1)[c(1,2,3)] <- c("Element", "Left MNE", "Right MNE")
#ensure no duplicate lines
data3 <- data3 %>%
  distinct()
#add row
new_row <- c(5,2,2,0.1,"cervus")
data_Copy <- rbind(data1, new_row)
#add column
new_col <- data2[c(2)]
colnames(new_col)[c(1)] <- c("New Column")
data2 <- cbind(data2, new_col)
#melting
data4 <- melt(data1, na.rm = FALSE, value.name = "Count", id = "Element")
data3_melt <- melt(data3, id.vars = "Species", variable.name = "Metric", value.name = "Value")
#set rownames
data1 %>%
  remove_rownames() %>%
  column_to_rownames(var = "Element")
#rownames to column
data5 <- data.frame(names = row.names(data5), data5)
    #OR
data5 <- data5_base
data5 <- cbind(rownames(data5), data.frame(data5, row.names = NULL))
    #OR (in %>%)
data5 <- data5_base
data5 <- data5 %>%
  rownames_to_column(var = "Car")
#column typing
data2$`New Column` <- as.factor(data2$`New Column`)
  #can also do character and numerical
#pivot_wider
data4 <- pivot_wider(data4, names_from = Element, values_from = Count)
#string manipulation
data_Copy <- data_Copy %>%
mutate(Element = str_replace(Element, "D_", "Distal ")) %>%
mutate(Element = str_replace(Element, "P_", "Proximal "))
#separating out row values onto different ones
data5 <- data5 %>%
  separate_rows(Car, sep = " ")


#To Add - joins both long and short, string pad, merge function, str_split_fixed
```

```{r subsetting types}
data1 <- data1_base
data2 <- data2_base
data3 <- data3_base
# keep only some columns by number
data1 <- data1[,c(1,2,3,4)]
# keep only some rows by number
data2 <- data2[c(1,2,3,4),]
# keep with both
data2 <- data2[2:4,3:4]
# keep only some columns by name
data3 <- data3[,c("Sepal.Width", "Species")]
# sort by column values - ascending is default
data3 <- data3 %>%
  arrange(desc(Sepal.Width))
#filter by name
data3 <- data3 %>%
  filter(Species == "setosa"|Species == "versicolor")
data3 <- subset(data3, Species=="versicolor")
#OR
data1 <- data1[data1$Element != "Mandible",]
data1 <- data1 %>%
  subset(Element != "Scapula")
#remove NAs
#can be done in some functions with is.na = FALSE
data1 <- data1[complete.cases(data1[,2]),]
#replace NAs
#must be consistent about data type
data1$UnSided_MNE <- replace_na(data1$UnSided_MNE, 0)



#To Add - Sort, remove NAs, filter by partial string, filter by numerical, coalesce, split and join strings in columns
```

```{r Simple Calculations}
data1 <- data1_base
data2 <- data2_base
data3 <- data3_base
# to add - simple addition of columns, cumsum, 
data4 <- data2
#basic arithmetic
var <- sum(data4$`Total_%`)
data4$addition <- data4$Payne_Meat + data4$Payne_Milk
data4$subtraction <- data4$Payne_Meat - data4$Payne_Milk
data4$div <- data4$Payne_Meat/data4$Payne_Milk
data4$multi <- data4$Payne_Meat*data4$Payne_Milk
#cumulative sum
data4$PercentCheck <- cumsum(data4$`Total_%`)
```

