---
title: "Document Startup Boilerplate etc."
author: "Jack Sudds"
date: "2024-12-20"
output: github_document
---

Always switch output to "github_document" so that github bit looks better

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Apparent direct method to install all necessarily packages quickly

```{r Packages}
if (!require("pacman")) install.packages("pacman")
library(pacman)
p_load(
  #Learning & Base
  learnr, swirl, installr,
  #File & Package Management
  here, rio, openxlsx, renv, pacman, remotes, readxl,
  #Data Management
  tidyverse, linelist, naniar, parsedate, reshape2, dplyr,
  #Stats
  janitor, gtsummary, rstatix, broom, lmtest, easystats, skimr, spatstat,
  #Plots
  cowplot, RColorBrewer, ggnewscale, wesanderson, DiagrammeR, incidence2, gghighlight, ggtext, ggrepel, gganimate, ggsci, grates, gridExtra, ggforce, hexbin, plotly,
  #GIS
  sf, tmap, spdep, rnaturalearth, rnaturalearthdata, broom, ggmap, mapdata, maps, spData, BiocManager, geoR, giscoR,
  #Reports & Dashboards
  rmarkdown, reportfactory, officer, flexdashboard, shiny,
  #tables
  knitr, flextable, formattable, gt,
  #Other
  kableExtra, psych, BSDA, htmltools, rgl, lubridate, htmlwidgets,
  #Testing
  raster, dismo, terra, CCAMLRGIS, tigris, patchwork
)

#set theme for plots
theme_set(theme_linedraw())
```

Basic Method for manually installing individual packages

```{r}
install.packages("learnr")
library(learnr)
```

