---
title: "Graph Creation"
author: "Jack Sudds"
date: "2024-12-20"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r Packages}
if (!require("pacman")) install.packages("pacman")
library(pacman)
p_load(
  #Learning & Base
  learnr, swirl, installr,
  #File & Package Management
  here, rio, openxlsx, renv, pacman, remotes, readxl,
  #Data Management
  tidyverse, linelist, naniar, parsedate, reshape2, dplyr,
  #Stats
  janitor, gtsummary, rstatix, broom, lmtest, easystats, skimr, spatstat,
  #Plots
  cowplot, RColorBrewer, ggnewscale, wesanderson, DiagrammeR, incidence2, gghighlight, ggtext, ggrepel, gganimate, ggsci, grates, gridExtra, ggforce, hexbin, plotly,
  #GIS
  sf, tmap, spdep, rnaturalearth, rnaturalearthdata, broom, ggmap, mapdata, maps, spData, BiocManager, geoR, giscoR,
  #Reports & Dashboards
  rmarkdown, reportfactory, officer, flexdashboard, shiny,
  #tables
  knitr, flextable, formattable, gt,
  #Other
  kableExtra, psych, BSDA, htmltools, rgl, lubridate, htmlwidgets,
  #Testing
  raster, dismo, terra, CCAMLRGIS, tigris, patchwork
)
```

```{r Test Data}
rm(list = ls(all.names = TRUE))
data1 <- read.xlsx(here("Data/data.xlsx"), sheet = "skeletal_part_abundances")
data2 <- read.xlsx(here("Data/data_2.xlsx"), sheet = "Sheep_Mandibles")
data3 <- iris
data4 <- mtcars
```

```{r Basic Graphs and Aesthetic Options}
# Point plot

ggplot(data3, aes(x = Sepal.Length, y=Sepal.Width, colour = Species, shape = Species)) +
  geom_point() +
#Include line
  geom_vline(xintercept = 6, linewidth = 0.5, color = "orange") +
#Examples of the kinds of details which can be altered in a theme
  theme(
    plot.title = element_text(hjust = 0.5, face = 'bold'),
        plot.subtitle = element_text(hjust = 0.5),
        panel.background = element_rect(fill = 'white'),
        panel.grid = element_line(color = 'grey'),
        axis.line = element_line(color = 'black'),
        panel.grid.minor.x = element_line(color = 'white'),
        panel.grid.minor.y = element_line(color = 'grey'),
        panel.grid.major.y = element_line(color = 'darkgrey'),
    axis.text.x = element_text(angle = 90)
  ) +
#Specify details about legend
  guides(
#Specify text
    colour = guide_legend("guide title"),
#Remove guide
    #colour = "none"
#Alter order
    shape = guide_legend(order = 1)
  ) +
# Specify axis label and title text
  labs(
    title = "Title",
    subtitle = "Subtitle",
    x = "Complex Titles can contain other stuff, \u03B413C‰",
    y = expression("Log" [10]* " Ratio ")
  ) +
  scale_y_continuous(
#Breaks in axis
    breaks = seq(1.5,5,by = 0.2)
  ) +
  scale_x_continuous()
  #scale_color_brewer() +

# Bar chart using counts (..count.. is depreciated)

ggplot(data3, aes(x = Sepal.Length, fill = Species)) +
  geom_bar(stat = "count") +
#Second type of coord system
  coord_cartesian(
#Set axis limits
    xlim = c(4,8),
#Make bars sit on bottom row, also removes gaps
    expand = FALSE
  ) +
#Manually alter fill/colour related content
  scale_fill_manual(
#Change colours by including hex codes
    values = c('#1b9e77','#d95f02','#7570b3'),
#Change label contents
    labels = c("Setosa", "Versicolor", "Virginica")
    ) +
#Separate graph into collection of Smaller ones
  facet_wrap(
#Specify what to 
    ~Species,
#Scales can be individualised "free"/"free_x"
    scales = "free_y")

#Additional table in plot
#MWSTable <- data.frame(MWS = c("A", "B", "C", "D", "E", "F", "G", "H", "I"),
                       #Age_Min = c(0,5,7,12,24,30,61,86,154),
                       #Age_Max = c(5,7,12,24,30,61,86,154,"-"))
#annotation_custom(tableGrob(MWSTable, rows=NULL, theme = ttheme_default(base_size = 9)), xmin = "C", xmax = "E", ymin = 2, ymax = 7)

#Save previous plot
#ggsave("<filename.jpg/png>", dpi = <size>)
```

```{r Specific/Unique Plots}
# To Add - Box plots, Line of best fit, 
```

