---
title: "Mapping"
author: "Jack Sudds"
date: "2024-12-20"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r Packages}
if (!require("pacman")) install.packages("pacman")
library(pacman)
p_load(
  #Learning & Base
  learnr, swirl, installr,
  #File & Package Management
  here, rio, openxlsx, renv, pacman, remotes, readxl,
  #Data Management
  tidyverse, linelist, naniar, parsedate, reshape2, dplyr,
  #Stats
  janitor, gtsummary, rstatix, broom, lmtest, easystats, skimr, spatstat,
  #Plots
  cowplot, RColorBrewer, ggnewscale, wesanderson, DiagrammeR, incidence2, gghighlight, ggtext, ggrepel, gganimate, ggsci, grates, gridExtra, ggforce, hexbin, plotly,
  #GIS
  sf, tmap, spdep, rnaturalearth, rnaturalearthdata, broom, ggmap, mapdata, maps, spData, BiocManager, geoR, giscoR,
  #Reports & Dashboards
  rmarkdown, reportfactory, officer, flexdashboard, shiny,
  #tables
  knitr, flextable, formattable, gt,
  #Other
  kableExtra, psych, BSDA, htmltools, rgl, lubridate, htmlwidgets,
  #Testing
  raster, dismo, terra, CCAMLRGIS, tigris, patchwork
)
```

```{r Test Data}
rm(list = ls(all.names = TRUE))
dataframe <- iris
```

```{r Basic maps}
#Most Basic
#load basemap data
Base_map <- ne_countries(scale = "large", returnclass = "sf", country = "united kingdom")
world <- ne_countries(scale = "medium", returnclass = "sf")
class(world)

#imaginary data
data1 <- dataframe
data1$Sepal.Length <- (data1$Sepal.Length*-1)+3
data1$Sepal.Width <- (data1$Sepal.Width*10)+20

#plot like a graph - USING IMAGINARY DATA HERE
ggplot(Base_map) +
  geom_sf() +
  theme_bw()+
  labs(
    title = "A Title",
    subtitle = "A Subtitle",
    x = "Longitude",
    y = "Latitude"
  )+
#ABILITY TO ADD LABELS
#geom_label_repel(data = BaseMap, aes(label = *needs to be specifically created*, x = long, y = lat, fontface = "bold"),label.size = NA, fill = "#FF0000", color = "black", segment.colour = "#FF0000", max.overlaps  = Inf, min.segment.length = 0)+
  coord_sf(xlim = c(-8,1), ylim = c(49,62),
             expand = FALSE) +
  geom_point(data1, mapping = aes(x = Sepal.Length, y = Sepal.Width), size = 1.5) 
```

```{r Grid Map}

```

```{r Splotch map}

```

```{r Maps as HTML dohickys}

```

